<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1" isELIgnored="false"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>  
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="<%=request.getContextPath()%>/resources/bootstrap/css/bootstrap.min.css" type="text/css">
	<link rel="stylesheet" href="<%=request.getContextPath()%>/resources/css/style.css" type="text/css">
	<link rel="stylesheet" href="<%=request.getContextPath()%>/resources/css/font-awesome.css" type="text/css"> 
	<link rel="stylesheet" href="<%=request.getContextPath()%>/resources/css/animate.css" type="text/css">
	<link href='https://fonts.googleapis.com/css?family=Baloo' rel='stylesheet'>
  
    <title>Terms & Conditions :: Bookmymovie.com</title>
</head>
<body>

	<div class="head-all">	
		<%@ include file ="header.jsp" %>
	</div>
		
	<br><br><br><br>
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h1 style="text-align:center;">Terms & Conditions</h1><br><br>
				
				
<h5>TERMS OF SERVICE</h5>

<p>
This document is an electronic record in terms of The Information Technology Act, 2000 ("IT Act") and rules thereunder, and is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines ) Rules 2011, which mandates for publishing of rules and regulations, privacy policy and terms of use for access or usage of the application. This electronic record is generated by a computer system and does not require any physical or digital signatures.
</p>
<p>
The following are the terms of service (hereinafter referred to as Terms) that govern your use/access of this website/application software, its related content, all associated sites and hyperlinks build, owned, maintained and or operated by Bookmymovie Private Limited and or its Affiliates and the domain name is owned by one of its Affiliates. These Terms applies to all users of the Website. 
</p>
<p>
These Terms may be read as a stand-alone document or be read with such other documents as may apply to Bookmymovie Wallet account or any other particular services. We may make changes to these Terms at any time. Any changes we make will be effective immediately when we post a revised version of these Terms on the Website. By continuing to use this Website after such changes, shall constitute your consent to any such changes. 
</p>
<p>
Our Services are diverse, so sometimes specific terms and/or additional terms (including age requirements) may apply when you avail our Services. Additional terms will be available with the relevant Services and/or offers, and those additional terms become part of these Terms, if you use of those Services.
</p>

<h5>1. DEFINITIONS</h5>
<p>
For the purpose of this Term,
</p>
<p>
"Affiliate(s)" shall mean with respect to Bookmymovie, any person directly or indirectly controlling, controlled by, or under direct or indirect common control with Bookmymovie including its holding company and or its subsidiaries and associate companies
<br>"Bookmymovie"/ "we"/ "us"/ "our" shall mean Bookmymovie Private Limited having its registered office at Delhi or its Affiliates. 
<br>"Service(s)" shall mean all services that Bookmymovie provides to its users through this Website including but not limited to booking of movie tickets and other added services. 
<br>"You"/ "User" shall mean the end user accessing the Website, its contents and or using the Services offered through the Website.
<br>"Website" means the website (www.Bookmymovie.in) and or application software (app) operated by Bookmymovie and or its Affiliates, which provides information to the users or any prospective customers and enable them to avail the Service(s) which may be offered by us from time to time.
</p>

<h5>2. ACCOUNT REGISTRATION</h5>
<p>
You need to register on our Website to avail our Services by verifying either your mobile number or email address and providing your name and other personally identifiable information. To protect your Bookmymovie account, keep your login credentials viz., password and OTP confidential. You are solely responsible for all the activity that happens on or through your Bookmymovie account, whether authorized by you or not. By registering, you hereby grant consent for contacting you via telephone or email based on the information furnished by you either by us, or our Affiliates or third parties nominated in this regard for providing better services or for promotional activities related to the Services. 
</p>
<p>
You agree that the basic customer information, personal identifiable information provided by you is true, complete and accurate, and agree not to submit any particulars which are false or any information you do not have any right or authority to provide. You are solely responsible for maintaining the confidentiality and security of all activities that occur on or through your access of the Website. 
</p>
<p>
In order to register with the Website you must be 18 (Eighteen) years of age or older. As a user of this Website, you are allowed to limited access of the Website, without registration. 
</p>

<h5>3. MOVIE TICKETS</h5>

<h5>3.1   Purchase of Movie Tickets</h5>

<p>
Bookmymovie acts as an intermediary to those who provide event services, including, but not limited to movie tickets (hereinafter referred to as "Event Providers"). When you purchase a ticket for an event, then Bookmymovie will act as an intermediary, handling the transaction as well as collecting payment for the Event Provider. 
</p>
<p>
Event Providers may choose to show only the base ticket price (i.e., without applicable taxes) while you are selecting seats on the Website. However, applicable taxes will be collected on the base ticket price at the time of making payment by you. You shall be completely responsible for all charges, fees, duties, taxes, and assessments arising out of the use of the Services. Further, you shall be responsible for any increase in the price charged by Event Providers on account of change in rate of taxes or imposition of new taxes by the Government.
</p>
<p>
By accessing or using the Website or by availing Services, You accept the following:
</p>
<p>
                               i.     You are instructed to satisfy yourself regarding the quality, quantity and fitness of any Service before purchasing the same. 

<br>                               ii.    Theatre layout shown on Website is only for illustration and to facilitate selection of your seat to watch the movie. Actual seat style and actual distance between screen and row may vary from those shown   on the Website. Tickets booked by you cannot be cancelled, exchanged or refunded

<br>                               iii.    Your booking confirmation will be sent via email, SMS and/or app notifications.

   <br>                            iv.    You or the person collecting the ticket(s) on your behalf, need to show an email print out or SMS confirmation in order to avail a physical ticket at the theatre counter.

       <br>                        v.    The holder of a physical ticket is deemed to be the owner of the ticket(s).

           <br>                   vi.    A convenience fee is levied on all tickets booked by you online. 

               <br>                vii.    You need to make bookings for tickets for children above the age of 3 years.

                   <br>            viii.    You are limited to a specified number of ticket booking on our Website for each event (also known as a "ticket limit"). This ticket limit is posted during the purchase process and is verified with every transaction. This policy is in effect to discourage unfair ticket buying practices. We reserve the right to cancel any or all orders and tickets without notice to you if you exceed the posted limits. This includes orders associated with the same email address, mobile number, or other information.

 <br>                              ix.    You will adhere to and comply with the terms and conditions of the respective theatres with respect to all the bookings made by you for tickets through the Website. 

     <br>                          x.    If you do not receive an order confirmation (in the form of a confirmation SMS or email or app notification) after submitting payment information, or if you receive an error message or service interruption after submitting payment information, you would immediately report to the Bookmymovie customer care. Only you may be aware of any problems that may occur during the purchase process and Bookmymovie will not be responsible for any losses occurred in the process. 

         <br>                      xi.    Any amount transferred erroneously by you to any theatre shall not be refunded to you by Bookmymovie under any circumstances.

             <br>                  xii.    If a movie is cancelled by the theatre and you purchased your ticket through Bookmymovie, we will automatically issue you a refund only to the credit card, debit card, e-wallet, Internet banking account or any other payment method that you used to purchase that ticket.

                 <br>               xiii.    Bookmymovie is under no obligation to monitor the theatre and its services used by you. Any dispute with or complaint against any theatre must be directly resolved by you with the theatre. If you are unable to resolve your dispute with the theatre, you can ask a refund for the ticket booked through Website. We will review the case and decide if you are eligible for a refund. It is also clarified that Bookmymovie decision is final and conclusive in case of all eligible refunds arising out of any dispute between you and the theatre. 

                     <br>          xiv.    In the event of any dispute, Bookmymovie records shall be binding as the conclusive evidence of the transactions carried out through the use of Website. Bookmymovie shall not be responsible or liable for any deficiency in services provided by the theatre except a refund of the ticket booked through Website. 

                         <br>      xv.    We may cancel transferred tickets if they were obtained fraudulently or otherwise in violation of our Terms. If a movie is cancelled or rescheduled, only the original purchaser will be eligible for a refund.

                             <br>  xvi.    You are solely responsible to select your movie and your seat(s) before purchasing a ticket. Policies set forth by Event Providers/theatres generally prohibit us from issuing exchanges or refunds after a ticket has been purchased, or for lost, stolen, damaged or destroyed tickets.

                               <br>xvii.    Bookmymovie shall send all customer communications by SMS and/or email and the SMS shall be deemed to have been received by you after they have been submitted for delivery to the mobile phone operator.

                              <br> xviii.    You agree to receive all commercial messages including transactional messages from Bookmymovie.
</p>
<h5>4. ASSISTED BOOKING OF MOVIE TICKETS </h5>
<p>
i.   Assisted Booking can help you to place an order for a movie ticket before the ticket booking opens on Website. 
<br>
ii.  You understand that the ticket will be booked on your behalf on a best-effort basis, based on tickets made available to Bookmymovie at the discretion of the theatre management and availability of such tickets cannot be guaranteed in any way. 
<br>
iii.  You will have to fill in the required details as mentioned in the Assisted Booking page such as day of release (i.e., 1st day, 2nd day or 3rd day of release), movie session, preferred class, number of seats etc., and place an order without which an Assisted Booking will be deemed incomplete.
<br>
iv.  You will have to load money in your Wallet account for the number of tickets placed under assisted booking. Bookmymovie will confirm your booking order on first come first serve basis and debit your wallet account at the time of confirming your movie ticket. Your movie ticket(s) will be not be confirmed, if there is insufficient balance in your Bookmymovie wallet account at the time of booking confirmation. 
<br>
v.   You can also use unified payments interface (UPI) or any other payment option as available on webpage to complete the assisted booking order. 
<br>
vi.  Money added to your Bookmymovie Wallet cannot be transferred back to your bank account. Once your assisted booking order is confirmed, tickets cannot be cancelled, nor will you be eligible for any refunds.
<br>
vii. Bookmymovie will not be responsible or liable for any wrong submission of required details including but not limited to day of release, session, number of seats etc., and non-availability of tickets for sale by Bookmymovie.
</p>

<h5>5. CHEERS</h5>
<p>
You can offer screening of your greetings/wishes to your friends or relatives for their birthday, wedding, anniversary, or any celebration ('Cheers') during the intermission of the movie, in the form of audio visual slides or graphical representation or both in digital format (‘Order’) at our network theatres. We accept to publish your Orders on these terms and conditions set out below: 
<br>
(i)   You are instructed to satisfy yourself by preview of your Order regarding the quality, quantity and fitness.
<br>
(ii)  Your Order confirmation will be sent via an e mail and/or SMS.
<br>
(iii) Booking for the Orders once made by you cannot be cancelled, postponed or refunded.
<br>
(iv)   If a movie is cancelled, our responsibility is limited to issue you a refund for your Orders to the credit card, debit card, e-wallet, Internet banking account or any other payment method that you used to purchase that Order.
<br>
(v) You shall be solely responsible for your own message submissions/Order and the consequences of posting or publishing them.
<br>
(vi) We reserve the right to decide whether content of your Order or your message is appropriate and complies with these terms. We may, without any responsibility to you, reject, cancel or require any Order to be amended that it considers unsuitable or contrary to these terms at any time and for any reason whatsoever. 
<br>
(vii)   You guarantee that 
<br>
-  any information supplied in connection with the Order is accurate, complete and not misleading;
<br>
-  You have obtained the consent of any person whose name (in whole or in part) is contained in any order;
<br>
(viii) You agree that You will not 
<br>
-  Post advertisements or solicitation of business including marketing and sales activities of goods or services.
<br>
-  Submit content or messages which are unlawful, abusive, insulting, threatening, harassing, hateful or is otherwise inappropriate. 
<br>
(ix)    You agree to authorise Bookmymovie and its affiliates to allow Your Orders to be published in conjunction with advertisements and to promote our service or websites/app.
<br>
(x)      All other Bookmymovie terms and conditions contained on the website shall apply.
<br>
<h5>6. RETRIEVE BOOKING</h5>
<br>
Our network theatres may offer you the option to block your ticket(s) at the theatre counter with or without making a payment for that ticket at the theatre counter. This also enables you to pay at a later date on the Website or at the ticket counter directly but within the time limit set by the theatre before the start of the show. 
<br>
i.           You will have to provide your mobile number or email address at the theatre counter to generate a unique code ('Booking Code') to block your selected ticket(s). The Booking Code will be sent to your mobile number or email address for making payment for such ticket(s) on the Website or at the ticket counter directly.
<br>
ii.         The Retrieve Booking option on the Website allows you to enter your Booking Code and confirm your email address and/or mobile number used to place the booking,
<br>
iii.        You will have to pay the transaction amount which includes the convenience fee and applicable taxes to get your ticket confirmed.
<br>
iv.       Your Booking Code will become invalid, if you fail to make payment against your retrieve booking code within the maximum time set by the theatre before the show timings.
<br>
v.         Bookmymovie shall not be responsible for any failure to receive submission due to transmission failures and other conditions beyond its reasonable control or any late transmission or entries provided by you.' 
<br>

<h5>8. CODE OF CONDUCT</h5>
<br>
You agree that you will comply with all applicable laws, rules and regulations, and that you will not:
<br>
- Restrict or inhibit any other person from using the Website;
<br>
- Use the Website for any unlawful purpose;
<br>
- Express or imply that any statements you make are endorsed by us, without our prior written consent;
<br>
- Impersonate any person or entity, whether actual or fictitious, including any employee or representative of our company;
<br>
- Submit (a) any content or information that is unlawful, fraudulent, libellous, defamatory, or otherwise objectionable, or infringes our or any third party-s intellectual property or other rights; (b) any non-public information about companies without authorization; or (c) any advertisements, solicitations, chain letters, surveys, contests, investment opportunities or other unsolicited commercial communication;
<br>
- Submit, or provide links to, any postings containing material that could be considered harmful, obscene, pornographic, sexually explicit, indecent, lewd, violent, abusive, profane, insulting, threatening, harassing, hateful or otherwise objectionable, includes the image or likeness of individuals under 18 years of age, encourages or otherwise depicts or glamorizes drug use (including alcohol and cigarettes), characterizes violence as acceptable, glamorous or desirable, or contains any personal contact information or other personal information identifying any third party;
<br>
- Display, upload, publish, distribute, share any information that threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states or public order or causes incitement to the commission of any cognizable offence or prevents the investigation of any offence or insults any other nation;
<br>
- Submit, or provide links to, any postings containing material that harasses, victimizes, degrades, or intimidates an individual or group of individuals on the basis of religion, race, ethnicity, sexual orientation, gender, age, or disability;
<br>
- Engage in spamming or flooding;
<br>
- Harvest or collect information about Website users;
<br>
- Order a number of tickets for an event that exceeds the stated limit for that event; or
<br>
- Use any area of the Website for commercial purposes, such as to conduct sale of tickets, products or services.
<br>
<h5>9. OWNERSHIP OF CONTENT</h5>
<br>
The Website and all data, text, designs, pages, print screens, images, artwork, photographs, audio and video clips, and HTML code, source code, or software that resides or is viewable or otherwise discoverable on the Website (collectively, the "Content") are owned by us. We own a copyright and, in many instances, patents and other intellectual property in the Website and Content. We may change the Content and features of the Website at any time.
<br>
We grant you a limited, conditional, no-cost, non-exclusive, non-transferable, non-sub-licensable license to view this Website and its Content to purchase tickets as permitted by these Terms for non-commercial purposes only if, as a condition precedent, you agree that you will not:
<br>
- Submit any software or other materials that contain any viruses, worms, Trojan horses, defects, date bombs, time bombs or other items of a destructive nature.
<br>
- Manipulate identifiers, including by forging headers, in order to disguise the origin of any posting that you submit.
<br>
- Link to any portion of the Website other than the URL assigned to the home page of our Website.
<br>
- "Frame" or "mirror" any part of the Website.
<br>
- Modify, adapt, sub-license, translate, sell, reverse engineer, decompile or disassemble any portion of the Website or otherwise attempt to derive any source code or underlying ideas or algorithms of any part of the Content.
<br>
- Remove any copyright, trademark or other proprietary rights notices contained on the Website.
<br>
- Use any robot, spider, offline reader, site search/retrieval application or other manual or automatic device, tool, or process to retrieve, index, data mine or in any way reproduce or circumvent the navigational structure or presentation of the Content or the Website, including with respect to any CAPTCHA displayed on the Website. Operators of public search engines may use spiders to copy materials from the Website for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials. We may revoke this exception at any time and require removal of archived materials gathered in the past.
<br>
- Use any automated software or computer system to search for, reserve, buy or otherwise obtain tickets, discount codes, vouchers, gift cards or any other items available on the Website, including sending information from your computer to another computer where such software or system is active.
<br>
- Take any action that imposes or may impose (in our sole discretion) an unreasonable or disproportionately large load on our infrastructure.
<br>
- Access, reload or refresh transactional event or ticketing pages, or make any other request to transactional servers, more than once during any three-second interval.
<br>
- Request more than 1,000 pages of the Website in any 24-hour period, whether alone or with a group of individuals.
<br>
- Make more than 800 reserve requests on the Website in any 24-hour period, whether alone or with a group of individuals.
<br>
- Reproduce, modify, display, publicly perform, distribute or create derivative works of the Website or the Content.
<br>
The registered and unregistered trademarks, logos and service marks displayed on the Website are owned by us. You may not use our trademarks, logos and service marks in any way without our prior written permission. You may inquire about obtaining permission by writing.
<br>
We may provide law enforcement with your personal identifiable information or information you provide to us related to your transactions to assist in any investigation or prosecution of you. If we are unable to verify or authenticate any information you provide during any registration, ordering, purchase, ticket posting, sale, authentication, delivery, payment or remittance process, or any other process, or if we are no longer able to verify or authorize your credit card or bank account information or e-wallet credentials, your tickets may be cancelled, we may refuse to honor all pending and future ticket purchases made with those credit card or e-wallet account or bank accounts and/or via any online accounts associated with those credit card, e-wallet or bank accounts. We may also prohibit you from using the Website.
<br>
<h5>10. FORUMS AND USER CONTENT</h5>
<br>
We may host fan reviews, message boards, blog feeds, social media feeds and other forums found on the Website (collectively, "Forums"), and you may be able to submit suggestions, reviews, concepts, audio and video recordings, photographs, artwork or other materials to the Forums or other areas of the Website ("User Content").
<br>
You own all rights to your User Content. If you submit User Content to the Website, you grant us a worldwide, non-exclusive, transferable, sub-licensable, royalty-free right and license to use, reproduce, modify, create derivative works of, distribute, publicly perform, display, archive and commercialize your User Content, in our sole discretion, in all formats and in all media channels now known or hereinafter discovered, without any compensation or acknowledgment to you or anyone else. This license will not affect your ownership in your User Content, including the right to grant additional licenses to your User Content, except if it conflicts with these Terms. We are not obligated to post, display or otherwise use any User Content, or to attribute your User Content to you. You will not make or authorize any claim against us that our use of your User Content infringes any of your rights.
<br>
Statements, opinions and reviews posted by participants in a Forum may be inaccurate, offensive, obscene, threatening or harassing. We do not endorse and are not responsible for these postings. We will not be liable for any loss or harm caused by the posting or your reliance on information obtained through the postings.
<br>
You will be responsible for your User Content and the consequences of posting it. By submitting User Content, you represent to us that (i) you own, or have the necessary permission to submit the User Content and to grant the licenses to us under this section, and (ii) you have the written permission of every identifiable person in the User Content to use that person's name and likeness in the manner contemplated by the Website and these Terms or, if the person is a minor, the written permission of the minor's parent or legal guardian.
<br>
We will have the right (but not the obligation) to monitor the Website, the Forums and the User Content, and to disclose any User Content and the circumstances surrounding its submission in order to operate the Website properly, or to protect ourselves, our sponsors and our users, or to comply with legal obligations or governmental requests.
<br>
If we are notified that your User Content does not comply with these Terms, we may investigate the allegation and may decide to remove your User Content and cancel your account/username.
<br>
<h5>11.   INTELLECTUAL PROPERTY RIGHTS</h5>
<br>
All intellectual property rights in this web site, design, text, graphics, applications, software, underlying source code and all other aspects belong to us and or our Affiliates.
<br>
<h5>Copyright:</h5>
<br>
All Content included on the Website such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, and software is the property of Bookmymovie, its Affiliates or its content suppliers and is protected by the appropriate Intellectual Property Laws.
<br>
<h5>Trademarks:</h5>
<br>
The trademark 'Bookmymovie', its logo and other Services Marks and logos owned by and/or licensed to Bookmymovie. There will be certain trademarks of third parties whose products are made available on the Website, these marks are used for representation purpose only and Bookmymovie does not claim any rights over these trademarks.
<br>
<h5>12.CLAIMS OF COPYRIGHT INFRINGEMENT ON THE SITE</h5>
<br>
If you believe that your intellectual property rights have been used in a way that gives rise to concerns of infringement, please write to us with your concerns and we will try and answer your concerns.
<br>
Notices and counter-notices should be sent to Bookmymovie Private Limited, No. 42, Dr. Ranga Road, Mylapore, Chennai - 600004.
<br>
<h5>13.   LINKS</h5>
<br>
The Website contains links to other websites that may not be owned or operated by us. The fact that we may link to those websites does not indicate any approval or endorsement of those websites. We have no control over those websites. We are not responsible for the content of those websites, or the privacy practices of those websites. We strongly encourage you to become familiar with the terms of use and practices of any linked website. Your use of other websites is at your own risk and is subject to the terms of those websites. It is up to you to take precautions to ensure that whatever links you select or software you download (whether from the Website or other sites) is free of viruses, worms, Trojan horses, defects, date bombs, time bombs and other items of a destructive nature.
<br>
<h5>14.   PARENTAL CONTROLS</h5>
<br>
We cannot prohibit minors from visiting our Website, and must rely on parents and guardians to decide what materials are appropriate for children to view and purchase. There are parental control protections (such as computer hardware, software or filtering services) available that may assist you in limiting access to material that is harmful to minors. We do not endorse the products or services listed at these websites.
<br>
<h5>15.   ACCESS FROM OUTSIDE INDIA</h5>
<br>
TheWebsite is directed at people residing in India. We do not represent that User Content available on or through the Website is appropriate or available in other locations. We may limit the availability of the Website or any service or product described on the Website to any person or geographic area at any time. If you choose to access the Website from outside India, you do so at your own risk.
<br>
<h5>16.   RULES FOR SWEEPSTAKES, CONTESTS AND GAMES</h5>
<br>
In addition to these Terms, sweepstakes, contests, games or other promotions (collectively, "Promotions") made available through the Website may have specific rules that are different from these Terms. You have to become familiar and agree with the terms and conditions of such specific rules before using Promotions.
<br>
<h5>17.  MOBILE DEVICE APPLICATION</h5>
<br>
If you install or use our mobile application, software and services, including any accompanying documentation, we grant you a limited right to install and use the App on devices located in India. You may use the App for your personal, non-commercial and entertainment purposes only. We do not grant you any rights to any related documentation, support, upgrades, maintenance or other enhancements to the App. We will not provide you with any device, internet access or wireless connection to use the App. We are not responsible for any interaction between you and another App user, or information you transmit through the App (including your location).
<br>
<h5>18.   GRIEVANCE REDRESSAL MECHANISM:</h5>
<br>
You have the right to register your complaint if you are not satisfied with our Services or finds deficiencies when dealing with agents/ staff or finds system errors. The following are the steps to address your grievance:
<br>
-     You can raise a complaint by email or by reaching customer care number provided on the Website. 
<br>
-     The complaint by e-mail shall be acknowledged by an immediate system generated reply or via manual e-mail to the extent possible.
<br>
-     The follow up action taken or once the complaint is resolved shall be informed to you by e-mail.
<br>
If you are not satisfied on the resolved complaint, you can escalate the issue by writing a letter to The Head Customer Support, Bookmymovie Private Limited, No. 42, Dr. Ranga Road, Mylapore, Chennai - 600 004 or by email to support@Bookmymovie.in. 
<br>
Estimated timeframe to address the queries or complaints raised by you: 
<br>
i)          You will receive immediate system response e-mail for any query raised via e-mail. 
<br>
ii)         First reply by Bookmymovie to you is within 24 hours. 
<br>
iii)       -In escalated issues, you will get a response within 5 working days from the date of receipt of the letter/e-mail by Bookmymovie.
<br>
<h5>19.   VIOLATION OF THESE TERMS</h5>
<br>
We may investigate any violation of these Terms, including unauthorized use of the Website. We may take legal action that we feel is appropriate. You agree that monetary damages may not provide us a sufficient remedy and that we may pursue injunctive or other relief for your violation of these Terms. If we determine that you have violated these Terms or the law, or for any other reason or for no reason, we may cancel your Bookmymovie Wallet, delete all your User Content and prevent you from accessing the Website at any time without notice to you. You will still be bound by your obligations under these Terms. You agree that we will not be liable to you or any third party for termination of your access to the Website or to Bookmymovie Wallet or any related information, and we will not be required to make the Website or Bookmymovie Wallet or any related information available to you. We may also cancel any ticket or merchandise order, and tickets or merchandise acquired through your order. We may refuse to honor pending and future purchases made from all accounts we believe may be associated with you, or cancel a ticket or ticket order associated with any person we believe to be acting with you, or cancel your ticket postings, or exercise any other remedy available to us. 
<br>
<h5>20.   DISCLAIMER OF WARRANTIES</h5>
<br>
We provide the Website and the Content to you "as is" and "as available". We try to keep the Website up, bug-free and safe, but you use it at your own risk. To the fullest extent permissible by law, we disclaim all warranties, express or implied, including any warranty of title, non-infringement, accuracy, merchantability, fitness for a particular purpose, or warranties that may arise from course of dealing or course of performance or usage of trade. We do not guarantee that the Website will always be safe, secure or error-free or that the Website will always function without disruptions, delays or imperfections. We are not responsible for the actions or information of third parties including but not limited to the theatres, and you release us from any claims and damages, known and unknown, arising out of or in any way connected with any claim you have against any such third parties 
<br>
<h5>21.   LIMITATION OF LIABILITY</h5>
<br>
In no event will we or our event providers, suppliers, advertisers and sponsors, be responsible or liable to you or anyone else for, and you hereby knowingly and expressly waive all rights to seek, direct, indirect, incidental, special or consequential damages of any type other than out of pocket expenses, and any rights to have damages multiplied or otherwise increased, arising out of or in connection with the Website, the User Content, or any Product or Service purchased through the Website, even if we have been advised of the possibility of such damages, and regardless of whether the claim is based upon any contract, tort, or other legal or equitable theory. Without limiting the foregoing, you expressly acknowledge and agree that we will have no liability or responsibility whatsoever for (a) any failure of another user of the Website to conform to the codes of conduct, (b) personal injury or property damage, of any nature whatsoever, whether arising in contract or in tort, resulting from your access to and use of our Website, (c) any unauthorized access to or use of our secure servers and/or any and all personal information and/or financial information stored therein, (d) any bugs, viruses, worms, trojan horses, defects, date bombs, time bombs or other items of a destructive nature which may be transmitted to or through our Website, (e) any errors, mistakes, inaccuracies or omissions in any content, or (f) any lost, stolen or damaged tickets, or the failure of a venue to honor a ticket. Your sole and exclusive remedy for dissatisfaction with the Website is to stop using the Website.
<br>
<h5>22.   INDEMNIFICATION</h5>
<br>
If anyone brings a claim against us related to your use of the Website, your User Content or your violation of these Terms, you agree to indemnify, defend and hold us and our affiliated companies, event providers, suppliers, advertisers and sponsors, and each of our officers, directors, employees, and agents, harmless from and against any and all claims, damages, losses and expenses of any kind (including reasonable legal fees and costs). We reserve the right to take exclusive control and defense of any claim, and you will cooperate fully with us in asserting any available defenses.
<br>
You agree to indemnify, defend and hold Bookmymovie and/or related parties harmless from any and all claims, losses, damages, and liabilities, costs and expenses, including and without limitation legal fees and expenses, arising out of or related to your use or misuse of the Bookmymovie Services including but not limited to Bookmymovie Wallet, any violation of these Terms, or any breach of the representations, warranties, and covenants made by you.
<br>
<h5>23.   ASSIGNMENT</h5>
<br>
Bookmymovie shall have the right to assign/transfer these presents to any third party including its holding company, subsidiaries, affiliates, associate group companies.
<br>
<h5>24.   CHOICE OF LAW AND DISPUTE RESOLUTION</h5>
<br>
These Terms shall be governed by, and construed in accordance with, the laws of India, without reference to principles of conflicts of law. You agree that the courts of Chennai shall have exclusive jurisdiction over any dispute arising from or relating to these Terms. 
<br>
<h5>25.   GENERAL</h5>
<br>
i.  The parties are independent contractors and nothing in these Terms shall be deemed to create an agency or employment relationship, a franchisor-franchisee relationship, joint venture or partnership.
<br>
ii.  These Terms constitute the entire agreement between you and us regarding its subject matter and supersede all prior and contemporaneous undertakings and agreements between the parties, whether written or oral, with respect to that subject matter.
<br>
iii.  If any provision of these Terms be deemed unenforceable or invalid, the other provisions of these Terms shall remain in full force and effect. 
<br>
iv.  You cannot assign or delegate your obligations under these Terms without the express written consent of Bookmymovie. </p>
				
			</div>
		</div>
	</div>	
	<br><br><br><br><br><br>
				
	<%@ include file ="footer.jsp" %>
		
	<!--my javascript-->
	<script src="<%=request.getContextPath()%>/resources/js/accordion.js"></script>
	<!--/my javascript-->
		
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="<%=request.getContextPath()%>/resources/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>